"""
Data Analysis Agent — FastAPI Backend

Exposes a Server-Sent Events (SSE) endpoint that streams the PydanticAI agent's
reasoning, tool calls, tool results, and final answer to the client in real time.

Streaming strategy:
  - Text deltas are parsed on-the-fly to extract <thinking> tags (see ThinkingStreamParser).
  - Tool calls emit a synthetic "thinking" block derived from their arguments when no
    native thinking is available (e.g. OpenAI models).
  - Native ThinkingPartDelta events (e.g. Anthropic extended thinking) take priority
    and suppress the synthetic fallback.

SSE event types emitted:
  - "thinking"    : reasoning content (native or synthetic)
  - "tool_call"   : tool invocation with name and arguments
  - "tool_result" : tool output, with optional Plotly file path
  - "text"        : final answer delta
  - "done"        : signals end of stream
  - "error"       : unexpected error during generation
"""

import json
import re
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv
from fastapi import FastAPI, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from pydantic_ai import (
    AgentRunResultEvent,
    FunctionToolCallEvent,
    FunctionToolResultEvent,
    PartDeltaEvent,
    PartStartEvent,
    TextPartDelta,
    ThinkingPartDelta,
)
from pydantic_ai.messages import ToolCallPart

load_dotenv()

from agent.agent import create_agent
from agent.context import AgentContext

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(title="Data Analysis Agent API")

# Allow all origins in development. Restrict to the frontend origin in production.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve Plotly HTML outputs generated by the visualize tool.
output_dir = Path("output")
output_dir.mkdir(exist_ok=True)
app.mount("/output", StaticFiles(directory="output"), name="output")

# ---------------------------------------------------------------------------
# Dataset loading
# ---------------------------------------------------------------------------

def load_datasets(data_dir: str = "data") -> tuple[dict[str, pd.DataFrame], str]:
    """
    Load all CSV files from the data directory into in-memory DataFrames.

    Returns:
        datasets: mapping of sanitized dataset name → DataFrame
        dataset_info: human-readable summary injected into the agent's system prompt
    """
    data_path = Path(data_dir)
    if not data_path.exists():
        data_path.mkdir(parents=True, exist_ok=True)
        return {}, "No datasets available."

    datasets: dict[str, pd.DataFrame] = {}
    info_lines: list[str] = []

    for csv_file in sorted(data_path.glob("*.csv")):
        # Sanitize filename to a valid SQL table name
        name = re.sub(r"[^a-zA-Z0-9_]", "_", csv_file.stem).strip("_").lower()
        df = pd.read_csv(csv_file)
        datasets[name] = df
        cols = ", ".join(df.columns.tolist())
        info_lines.append(
            f"- **{name}** ({df.shape[0]} rows, {df.shape[1]} columns)\n"
            f"  Columns: {cols}"
        )

    if not info_lines:
        return {}, "No datasets available."

    return datasets, "\n".join(info_lines)


# Datasets are loaded once at startup and shared across requests.
# A server restart is required to pick up new CSV files.
datasets, dataset_info = load_datasets()
agent = create_agent(dataset_info)

# ---------------------------------------------------------------------------
# Request model
# ---------------------------------------------------------------------------

class ChatRequest(BaseModel):
    question: str

# ---------------------------------------------------------------------------
# SSE helper
# ---------------------------------------------------------------------------

def sse(event_type: str, data: dict) -> str:
    """Format a dict as a Server-Sent Event data line."""
    payload = json.dumps({"type": event_type, **data}, ensure_ascii=False)
    return f"data: {payload}\n\n"

# ---------------------------------------------------------------------------
# Thinking tag stream parser
# ---------------------------------------------------------------------------

class ThinkingStreamParser:
    """
    Parses <thinking>...</thinking> tags on-the-fly from a character stream.

    OpenAI models do not emit native ThinkingPartDelta events. Instead, the
    system prompt instructs the model to wrap its reasoning in <thinking> tags
    within the text stream. This parser separates those tags from the visible
    answer as the stream arrives, without waiting for the full response.

    Usage:
        parser = ThinkingStreamParser()
        for chunk in stream:
            for kind, content in parser.feed(chunk):
                emit(kind, content)  # kind is "thinking" or "text"
        for kind, content in parser.flush():
            emit(kind, content)      # flush any remaining buffered content
    """

    def __init__(self):
        self._buffer = ""
        self._in_thinking = False

    def feed(self, delta: str) -> list[tuple[str, str]]:
        """
        Feed a text delta and return (kind, chunk) pairs immediately emittable.

        A small tail of the buffer is always held back to handle tags that span
        chunk boundaries (e.g. "<think" in one chunk, "ing>" in the next).
        """
        results = []
        self._buffer += delta

        while self._buffer:
            if self._in_thinking:
                end = self._buffer.find("</thinking>")
                if end != -1:
                    # Emit everything up to the closing tag as thinking content
                    if end > 0:
                        results.append(("thinking", self._buffer[:end]))
                    self._buffer = self._buffer[end + len("</thinking>"):]
                    self._in_thinking = False
                else:
                    # Hold back the last 11 chars in case "</thinking>" spans chunks
                    safe = len(self._buffer) - 11
                    if safe > 0:
                        results.append(("thinking", self._buffer[:safe]))
                        self._buffer = self._buffer[safe:]
                    break
            else:
                start = self._buffer.find("<thinking>")
                if start != -1:
                    # Emit text before the opening tag, then switch to thinking mode
                    if start > 0:
                        results.append(("text", self._buffer[:start]))
                    self._buffer = self._buffer[start + len("<thinking>"):]
                    self._in_thinking = True
                else:
                    # Hold back the last 10 chars in case "<thinking>" spans chunks
                    safe = len(self._buffer) - 10
                    if safe > 0:
                        results.append(("text", self._buffer[:safe]))
                        self._buffer = self._buffer[safe:]
                    break

        return results

    def flush(self) -> list[tuple[str, str]]:
        """
        Flush any content remaining in the buffer at end of stream.

        Called once after the stream ends to ensure no content is lost.
        Unclosed <thinking> tags are emitted as thinking content.
        """
        results = []
        if self._buffer:
            kind = "thinking" if self._in_thinking else "text"
            results.append((kind, self._buffer))
            self._buffer = ""
        return results


# ---------------------------------------------------------------------------
# Streaming endpoint
# ---------------------------------------------------------------------------

@app.post("/api/chat")
async def chat(request: ChatRequest):
    """
    Stream the agent's response as Server-Sent Events.

    The generator iterates over PydanticAI's run_stream_events() and maps each
    event type to one or more SSE messages. Deduplication sets prevent duplicate
    tool_call / tool_result events that can occur when both FunctionToolCallEvent
    and PartStartEvent fire for the same tool invocation.
    """
    async def generate():
        context = AgentContext(datasets=datasets, dataset_info=dataset_info)

        # Track emitted IDs to avoid sending duplicate events for the same call
        emitted_tool_calls: set[str] = set()
        emitted_tool_results: set[str] = set()

        # Set to True once a native ThinkingPartDelta is received, which disables
        # the synthetic thinking fallback for the rest of the response.
        has_real_thinking = False

        try:
            parser = ThinkingStreamParser()

            async for event in agent.run_stream_events(request.question, deps=context):

                # --- End of generation ---
                if isinstance(event, AgentRunResultEvent):
                    # Flush any content still buffered in the parser
                    for kind, chunk in parser.flush():
                        if chunk.strip():
                            yield sse(kind, {"content": chunk})
                    yield sse("done", {"content": ""})

                # --- Tool call (rich event with full args) ---
                elif isinstance(event, FunctionToolCallEvent):
                    call_id = event.part.tool_call_id
                    if call_id and call_id in emitted_tool_calls:
                        continue
                    try:
                        args = event.part.args_as_dict()
                    except Exception:
                        args = {}

                    # Skip early events emitted before args are fully streamed
                    if not args:
                        continue

                    if call_id:
                        emitted_tool_calls.add(call_id)

                    # Emit a synthetic thinking block derived from tool arguments.
                    # This gives users visibility into the agent's intent when the
                    # underlying model does not support native thinking output.
                    if not has_real_thinking:
                        thinking_lines = []
                        if "description" in args:
                            thinking_lines.append(args["description"])
                        if "sql" in args:
                            thinking_lines.append(f"SQL query: {args['sql']}")
                        if "title" in args:
                            thinking_lines.append(f"Visualization: {args['title']}")
                        if thinking_lines:
                            yield sse("thinking", {"content": "\n".join(thinking_lines)})

                    yield sse("tool_call", {
                        "tool": event.part.tool_name,
                        "args": args,
                        "call_id": call_id,
                    })

                # --- Part start (handles tool calls from providers using PartStartEvent) ---
                elif isinstance(event, PartStartEvent):
                    part = event.part
                    if isinstance(part, ToolCallPart):
                        call_id = part.tool_call_id
                        if call_id and call_id in emitted_tool_calls:
                            continue
                        try:
                            args = part.args_as_dict()
                        except Exception:
                            args = {}
                        if not args:
                            continue
                        if call_id:
                            emitted_tool_calls.add(call_id)
                        yield sse("tool_call", {
                            "tool": part.tool_name,
                            "args": args,
                            "call_id": call_id,
                        })

                # --- Text and thinking deltas ---
                elif isinstance(event, PartDeltaEvent):
                    delta = event.delta

                    if isinstance(delta, TextPartDelta) and delta.content_delta:
                        # Run through the parser to separate <thinking> from text
                        for kind, chunk in parser.feed(delta.content_delta):
                            yield sse(kind, {"content": chunk})

                    elif isinstance(delta, ThinkingPartDelta) and delta.content_delta:
                        # Native thinking (e.g. Anthropic extended thinking).
                        # Mark as real so the synthetic fallback is suppressed.
                        has_real_thinking = True
                        yield sse("thinking", {"content": delta.content_delta})

                # --- Tool result ---
                elif isinstance(event, FunctionToolResultEvent):
                    call_id = event.tool_call_id
                    if call_id and call_id in emitted_tool_results:
                        continue

                    content = str(event.result.content)

                    # Detect Plotly HTML files saved by the visualize tool
                    plotly_file = None
                    if "Saved to:" in content:
                        match = re.search(r"Saved to: (output/[^\s]+)", content)
                        if match:
                            plotly_file = match.group(1)

                    if call_id:
                        emitted_tool_results.add(call_id)

                    yield sse("tool_result", {
                        "call_id": call_id,
                        "content": content[:500],  # truncate large results
                        "plotly_file": plotly_file,
                    })

        except Exception as e:
            from anyio import BrokenResourceError
            if isinstance(e, BrokenResourceError):
                # Client disconnected mid-stream — exit silently
                return
            yield sse("error", {"content": str(e)})

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",  # disable Nginx response buffering
        },
    )

# ---------------------------------------------------------------------------
# Upload dataset endpoint
# ---------------------------------------------------------------------------

@app.post("/api/upload")
async def upload_dataset(file: UploadFile = File(...)):
    global datasets, dataset_info, agent

    if not file.filename.endswith(".csv"):
        return {"error": "Only CSV files are supported."}

    # Sauvegarder dans data/
    save_path = Path("data") / file.filename
    content = await file.read()
    with open(save_path, "wb") as f:
        f.write(content)

    # Recharger tous les datasets et recréer l'agent
    datasets, dataset_info = load_datasets()
    agent = create_agent(dataset_info)

    # Infos sur le nouveau dataset
    name = re.sub(r"[^a-zA-Z0-9_]", "_", Path(file.filename).stem).strip("_").lower()
    df = datasets.get(name)

    return {
        "status": "ok",
        "name": name,
        "rows": len(df) if df is not None else 0,
        "columns": df.columns.tolist() if df is not None else [],
    }

# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

@app.get("/api/health")
async def health():
    """Return server status and the list of loaded datasets."""
    return {"status": "ok", "datasets": list(datasets.keys())}
